name: Chair Apparel
favicon: null
layout_spectrum: 0.983871
typography_spectrum: 1
title: Give your chair an identity for people to recognize
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000002'
    - '#ffffff'
    - '#01ffff'
    - '#84abb0'
    - '#663123'
  brandStrength: 0.375
  lightness: 0.9426523
  saturation: 0.6415621
  rhythmicContrast: 0.9042829
purpose: []
